title: Power Controls
type: container
tags: [hide-title]
hint: >-
  Power settings for your device.
children:
  tdp:
    type: mode
    title: TDP Mode
    default: balanced
    modes: {}
  sys_tdp:
    type: display
    title: " "
    tags: []

  fan: {}