title: Power Controls
type: container
tags: [hide-title]
hint: >-
  Power settings for your device.
children:
  tdp:
    type: mode
    title: Power Mode
    default: balanced
    modes: {}
  sys_tdp:
    type: display
    title: " "
    tags: []

  cycle_tdp:
    type: bool
    title: Change Power Mode with View+Y
    tags: [ non-essential ]
    hint: >-
      Allows you to cycle through power modes with the View+Y or Xbox+Y key combination.
    default: False

  fan_full_speed:
    type: bool
    title: Set Fan to Full Speed

  fan: {}
